[[redirects]]
from = "http://laurabrown.xyz"
to = "https://laurabrown.studio"
status = 301
force = true
[[redirects]]
from = "https://laurabrown.xyz"
to = "https://laurabrown.studio"
status = 301
force = true
[[redirects]]
from = "http://www.laurabrown.xyz"
to = "https://laurabrown.studio"
status = 301
force = true
[[redirects]]
from = "https://www.laurabrown.xyz"
to = "https://laurabrown.studio"
status = 301
force = true